server:
  port: 8080
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"

routes:
  paths:
    users: "/api/v1/users"
    userById: "/api/v1/users/{idUsuario}"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_auth"
    schema: "public"
    username: "postgres"
    password: "1234"
  main:
      web-application-type: reactive

# Configuración de OpenAPI (opcional)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  version: '1.0.0'
  title: 'CrediYa Authentication API'
  description: 'API for user management'